-- MySQL Script generated by MySQL Workbench
-- Mon Jun 30 12:28:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema littlelemondb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema littlelemondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `littlelemondb` DEFAULT CHARACTER SET utf8 ;
USE `littlelemondb` ;

-- -----------------------------------------------------
-- Table `littlelemondb`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Customers` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Customers` (
  `CustomerID` INT AUTO_INCREMENT,
  `FullName` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(100),
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Phone_UNIQUE` ON `littlelemondb`.`Customers` (`Phone` ASC);


-- -----------------------------------------------------
-- Table `littlelemondb`.`Bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Bookings` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Bookings` (
  `BookingID` INT AUTO_INCREMENT,
  `CustomerID` INT NOT NULL,
  `BookingDate` DATE NOT NULL,
  `TableNumber` INT ,
  PRIMARY KEY (`BookingID`),
  CONSTRAINT `CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `littlelemondb`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `CustomerID_idx` ON `littlelemondb`.`Bookings` (`CustomerID` ASC);


-- -----------------------------------------------------
-- Table `littlelemondb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Staff` (
  `StaffID` INT,
  `FullName` VARCHAR(100),
  `Role` VARCHAR(100),
  `Salary` DECIMAL(10,2) ,
  PRIMARY KEY (`StaffID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Orders` (
  `OrderID` INT AUTO_INCREMENT,
  `BookingID` INT NOT NULL,
  `OrderDate` DATE NOT NULL,
  `Quantity` INT ,
  `TotalCost` DECIMAL(10,2),
  PRIMARY KEY (`OrderID`),
  CONSTRAINT `BookingID`
    FOREIGN KEY (`BookingID`)
    REFERENCES `littlelemondb`.`Bookings` (`BookingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `BookingID_idx` ON `littlelemondb`.`Orders` (`BookingID` ASC);


-- -----------------------------------------------------
-- Table `littlelemondb`.`OrderDeliveryStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`OrderDeliveryStatus` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`OrderDeliveryStatus` (
  `StatusID` INT AUTO_INCREMENT,
  `OrderID` INT NOT NULL,
  `DeliveryDate` DATE ,
  `Status` VARCHAR(45) ,
  PRIMARY KEY (`StatusID`),
  CONSTRAINT `OrderID`
    FOREIGN KEY (`OrderID`)
    REFERENCES `littlelemondb`.`Orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `OrderID_idx` ON `littlelemondb`.`OrderDeliveryStatus` (`OrderID` ASC) ;


-- -----------------------------------------------------
-- Table `littlelemondb`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Menu` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Menu` (
  `MenuItemID` INT AUTO_INCREMENT,
  `Category` ENUM('Starter', 'MainCourse', 'Drink', 'Dessert') NOT NULL,
  `ItemName` VARCHAR(50),
  `Price` DECIMAL(10,2),
  PRIMARY KEY (`MenuItemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`OrderDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`OrderDetails` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`OrderDetails` (
  `OrderID` INT NOT NULL,
  `MenuItemID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  CONSTRAINT `fk_OrderDetails_OrderID`
    FOREIGN KEY (`OrderID`)
    REFERENCES `littlelemondb`.`Orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MenuItemID`
    FOREIGN KEY (`MenuItemID`)
    REFERENCES `littlelemondb`.`Menu` (`MenuItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `OrderID_idx` ON `littlelemondb`.`OrderDetails` (`OrderID` ASC);

CREATE INDEX `MenuItemID_idx` ON `littlelemondb`.`OrderDetails` (`MenuItemID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
